"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer";
import Header from "./Components/Header";

// Import the Inter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
  
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
      <title>Dragon Bull Run</title>
      <meta name="description" content="This is a brief description of the page content."/>


      </head>
      <body>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
